'use strict';

// Word delta for Roger: approved proposals rendered as paste-ready
// sections for the next master rule set version. Content building
// (deltaSections) is pure; buildDeltaDocx renders it with npm docx.

const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');
const { xmlSafeText } = require('./xml-safe-text');

// Sanitising lives in ONE place (xml-safe-text) so the door and this gate
// cannot drift apart — they previously held identical hand-copied regexes,
// which meant this gate shared the door's exact blind spot.
const safe = xmlSafeText;

// A rule with no text used to render as a heading, the label "Proposed rule
// text:" and a blank line — indistinguishable from a rule Roger must read.
const NO_TITLE = '[UNTITLED PROPOSAL — no flag title recorded]';
const NO_RULE_TEXT = '[NO RULE TEXT — the proposer submitted no description. Check before merging.]';

const TIERS = new Set(['rule', 'library']);

function fmtDate(iso) { return String(iso || '').slice(0, 10); }

function provenance(p) {
  return [
    `Source: certificate ${safe(p.certificate_ref)}` + (p.cert_type ? ` (EHC ${safe(p.cert_type)})` : '') + `, ${fmtDate(p.created_at)}.`,
    p.proposed_by ? `Proposed by ${safe(p.proposed_by)}.` : null,
    p.proposer_note ? `Proposer note: ${safe(p.proposer_note)}` : null,
    `Approved by ${safe(p.reviewed_by)} on ${fmtDate(p.reviewed_at)}` + (p.decision_note ? ` — ${safe(p.decision_note)}` : '') + '.'
  ].filter(Boolean);
}

function ruleText(p) {
  const preferred = safe(p.model_recommendation).trim();
  if (preferred) return preferred;
  return safe(p.flag_description).trim() || NO_RULE_TEXT;
}

function deltaSections(proposals, opts) {
  const list = proposals || [];
  const rules = list.filter((p) => p.tier === 'rule');
  const libs = list.filter((p) => p.tier === 'library');
  // A tier the renderer does not recognise must never make a proposal
  // vanish: the export records proposals as delivered, so one dropped here
  // is gone for good. Surfaced in the document instead of filtered away.
  const unclassified = list.filter((p) => !TIERS.has(p.tier));

  if (rules.length + libs.length + unclassified.length !== list.length) {
    throw new Error('delta-docx: tier buckets do not cover the input — refusing to build a partial delta');
  }

  const sections = [];

  // The document travels to Roger on its own; a warning that lives only in
  // the web UI does not reach him.
  const partial = opts && opts.partial;
  if (partial && Number.isFinite(partial.shipped) && Number.isFinite(partial.total)) {
    sections.push({
      heading: 'PARTIAL EXPORT — this document is incomplete',
      lines: [
        `This delta contains ${partial.shipped} of ${partial.total} approved proposals.`,
        partial.cause === 'parallel'
          ? 'The rest were exported by a parallel export and are in a separate document — they are NOT queued.'
          : partial.cause === 'error'
            ? 'The rest could not be recorded as exported and remain queued for the next delta.'
            : 'The rest are not in this document.'
      ]
    });
  }

  for (const p of rules) {
    sections.push({
      heading: safe(p.flag_title) || NO_TITLE,
      lines: ['Proposed rule text:', ruleText(p), ...provenance(p)]
    });
  }

  if (libs.length > 0) {
    sections.push({
      heading: 'Library additions',
      lines: libs.flatMap((p) => [`• ${safe(p.flag_title) || NO_TITLE}`, ruleText(p), ...provenance(p), ''])
    });
  }

  if (unclassified.length > 0) {
    sections.push({
      heading: 'Needs classification — review before merging',
      lines: unclassified.flatMap((p) => [
        `• ${safe(p.flag_title)} (tier recorded as ${safe(p.tier) || 'empty'})`,
        ruleText(p),
        ...provenance(p),
        ''
      ])
    });
  }

  return sections;
}

async function buildDeltaDocx(proposals, opts) {
  const sections = deltaSections(proposals, opts);
  const children = [
    new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun('EHC Checker — Rule set delta')] }),
    new Paragraph({ children: [new TextRun({ text: 'Approved proposals awaiting inclusion in the next master rule set version. Generated by the EHC Checker admin pipeline.', italics: true })] })
  ];
  for (const s of sections) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(safe(s.heading))] }));
    for (const line of s.lines) {
      children.push(new Paragraph({ children: [new TextRun(safe(line))] }));
    }
  }
  const doc = new Document({
    styles: { default: { document: { run: { font: 'Arial', size: 22 } } } },
    sections: [{
      properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      children
    }]
  });
  return Packer.toBuffer(doc);
}

module.exports = { deltaSections, buildDeltaDocx };
