'use strict';

// Word delta for Roger: approved proposals rendered as paste-ready
// sections for the next master rule set version. Content building
// (deltaSections) is pure; buildDeltaDocx renders it with npm docx.

const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');

function fmtDate(iso) { return String(iso || '').slice(0, 10); }

function provenance(p) {
  return [
    `Source: certificate ${p.certificate_ref}` + (p.cert_type ? ` (EHC ${p.cert_type})` : '') + `, ${fmtDate(p.created_at)}.`,
    p.proposer_note ? `Proposer note: ${p.proposer_note}` : null,
    `Approved by ${p.reviewed_by} on ${fmtDate(p.reviewed_at)}` + (p.decision_note ? ` — ${p.decision_note}` : '') + '.'
  ].filter(Boolean);
}

function ruleText(p) {
  return p.model_recommendation && p.model_recommendation.trim()
    ? p.model_recommendation.trim()
    : p.flag_description;
}

function deltaSections(proposals) {
  const rules = proposals.filter((p) => p.tier === 'rule');
  const libs = proposals.filter((p) => p.tier === 'library');
  const sections = rules.map((p) => ({
    heading: p.flag_title,
    lines: ['Proposed rule text:', ruleText(p), ...provenance(p)]
  }));
  if (libs.length > 0) {
    sections.push({
      heading: 'Library additions',
      lines: libs.flatMap((p) => [`• ${p.flag_title}`, ruleText(p), ...provenance(p), ''])
    });
  }
  return sections;
}

async function buildDeltaDocx(proposals) {
  const sections = deltaSections(proposals);
  const children = [
    new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun('EHC Checker — Rule set delta')] }),
    new Paragraph({ children: [new TextRun({ text: 'Approved proposals awaiting inclusion in the next master rule set version. Generated by the EHC Checker admin pipeline.', italics: true })] })
  ];
  for (const s of sections) {
    children.push(new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(s.heading)] }));
    for (const line of s.lines) {
      children.push(new Paragraph({ children: [new TextRun(String(line))] }));
    }
  }
  const doc = new Document({
    styles: { default: { document: { run: { font: 'Arial', size: 22 } } } },
    sections: [{
      properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 } } },
      children
    }]
  });
  return Packer.toBuffer(doc);
}

module.exports = { deltaSections, buildDeltaDocx };
